### ISSUE TITLE
Static main.js files not updating?

### ISSUE THREAD

**Issue by theluckylucas** [FrancescoSaverioZuppichini/mirror#10]
Thanks first of all for this great project!
I have never worked with react or alike before, but whatever I am changing in die app.js or others wont have any effect. In fact, the main.js et cetera in the static subfolder are never updated. What am I missing, so that these are updated?

**Comment by FrancescoSaverioZuppichini** [comment]
Hi :) Can you give me more info? You need to build the react app and them place manually the files inside [the static folder](https://github.com/FrancescoSaverioZuppichini/mirror/tree/master/mirror/static).  Sorry if there is no documentation, I am super busy these days (exams), from next week I will add all the steps to change the front-end.

**Comment by FrancescoSaverioZuppichini** [comment]
Hi @theluckylucas , I have just pushed a new release and I have added a small section in the Readme called Change the front-end, it should help you.

Now mirror supports multiple inputs, you can check the release logs [here](https://github.com/FrancescoSaverioZuppichini/mirror/releases)

**Comment by theluckylucas** [comment]
Dear @FrancescoSaverioZuppichini , wow - that was fast! Thanks a lot, it's excellent!
