### ISSUE TITLE
Unable to init server: Broadway display type not supported

### ISSUE THREAD

**Issue by h-sh-h** [FrancescoSaverioZuppichini/mirror#14]
Hi,
I'm trying to run your code on Ubuntu 18.04 but i get the following error :
```
 * Serving Flask app "mirror.server" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
 * Restarting with stat
Unable to init server: Broadway display type not supported: True
Error: cannot open display: True
```

**Comment by FrancescoSaverioZuppichini** [comment]
Hi,

That's weird, have you tried to google the error?

Can you share the code? 

Cheers,

Francesco

**Comment by h-sh-h** [comment]
Sorry, Turns out that I'm trying to run your code in Pycharm Ipython console. Works if you run it from terminal.

By the way, I think it's not a bad idea if you mention your other repository 
[https://github.com/FrancescoSaverioZuppichini/A-journey-into-Convolutional-Neural-Network-visualization-](url) for people like me who are new to visualization, since that repo was very informative !

Thanks

**Comment by FrancescoSaverioZuppichini** [comment]
Thank you for the nice feedback :)

I am glad you fix the bug.  You are correct, I should review the doc/readme but unfortunately, I am super busy with my master thesis. As soon as I finish it I will review this project and add more features and doc.

Cheers,

Francesco
