### ISSUE TITLE
Can I visualize my own model?

### ISSUE THREAD

**Issue by DaVilla7** [FrancescoSaverioZuppichini/mirror#15]
Is it only for the present classical models (alex,vgg or resnet)? How can I use it to visualize my own model (which is a pytorch model of faster r-cnn), where should I put the 'pth' model?

**Comment by FrancescoSaverioZuppichini** [comment]
Hi, just pass your model in the `mirror` function


`
model = // load your model
mirror(input, model, visualisations=[DeepDreamVis, BackPropVis, GradCamVis]
`
